
markdown: kramdown



# MyData
owner:
  name:           ChangGyu Jang
  avatar:         photo.jpg
  email:          wkdckdgur34@gmail.com

  #github:wkdckdrb
  # instagram:trip_savedata
 # tistory : 

highlighter: rouge
# text highlighter로 rouge이용
# 2016.02월 이후로 syntax highlighter는 rouge만 지원.
# Pygments 사용불가.

paginate: 10


language: 'en-uk'
# 언어 설정

url: https://wkdckdrb.github.io
asset_url: /assets

baseurl: /

title: Jang's Portfolio


description: The site that introduces my career


cover: assets/built/images/blog-cover1.jpg
# blog home에 표시될 blog cover image.

favicon: assets/built/images/favicon.ico

production_url: https://wkdckdrb.github.io/

source_url: 

# Social info
navigation: True


subscribers: True


permalink: /:title


plugins: [jekyll-paginate, jekyll-feed, jekyll-gist]

feed:
  path: feed.xml

safe: False
lsi: False

username: wkdckdrb
repo: GitHubPageMaker


branch: master


relative_source:

destination: ../[GitHubPage]/

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
  - node_modules
  - _posts/angular
  - _posts/et-cetera
#  - _posts/python
  - _posts/typescript
#  - _posts/jekyll
  - _posts/iot
  - _posts/r
  - _posts/economy
